//CommonJS, every file is a module (by default)
//Modules - Encapsulated code (only sare minimum)
const names = require('./04-names')
const sayHi = require('./05-utils')
const data = require('./06-alternative-syntax')
require('./07-mind-grenade')

sayHi('susan')
sayHi(names.jhon)
sayHi(names.peter)